name: Update draft specification
on:
  workflow_dispatch:
  push:
    branches: draft

jobs:
  build-draft:
    name: Make draft spec release
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6
      with:
        python-version: 3.x

    - name: Find pip cache dir
      id: pip-cache
      run: echo "::set-output name=dir::$(pip cache dir)"

    - name: pip cache
      uses: actions/cache@48af2dc4a9e8278b89d7fa154b955c30c6aaab09
      with:
        # Use the os dependent pip cache directory found above
        path: ${{ steps.pip-cache.outputs.dir }}
        # A match with 'restore-keys' is used as fallback
        key: ${{ runner.os }}-pip-

    - name: Clone
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

    - name: Build specification
      run: |
        python -m pip install bikeshed
        mkdir build && cd build
        make -f ../Makefile draft

    - name: Switch branch
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      with:
        ref: gh-pages
        clean: false

    - name: Push generated specification
      run: |
        git config user.name "TUF Specification Automation"
        git config user.email theupdateframework@googlegroups.com
        rm -fr draft
        mv build/* .
        rmdir build
        git add .
        git commit -m "Publish latest draft specification"
        git push
