name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  main:
    name: Check date and version are updated
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
        with:
          fetch-depth: 0 # we want all refs for the --is-ancestor check
      - name: Set up Python
        uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6
        with:
          python-version: 3.x
      - name: Check date and version
        run: python check_release.py
