name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  main:
    name: Sanity checks before a PR merge
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0 # we want all refs for the --is-ancestor check

      - name: Set up Python
        uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6
        with:
          python-version: 3.x

      - name: Find pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: pip cache
        uses: actions/cache@48af2dc4a9e8278b89d7fa154b955c30c6aaab09
        with:
          # Use the os dependent pip cache directory found above
          path: ${{ steps.pip-cache.outputs.dir }}
          # A match with 'key' counts as cache hit
          key: ${{ runner.os }}-pip-

      - name: Ensure changes build
        run: |
          python -m pip install bikeshed
          mkdir build && cd build
          make -f ../Makefile spec

      - name: Check date and version
        run: python check_release.py
