name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  main:
    name: Check date and version are updated
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          fetch-depth: 0 # we want all refs for the --is-ancestor check
      - name: Set up Python
        uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6
        with:
          python-version: 3.x
      - name: Check date and version
        run: python check_release.py
